title: Moritz Glöckl
pagetitle: Moritz Glöckl | gloeckl.me
tagline: IT Consultant & Software Developer
description: "Personal website of Moritz Glöckl - IT consulting and software development services based in Vienna, Austria."

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: :compressed

exclude: [README.md]