title: Moritz Glöckl
pagetitle: Moritz Glöckl | gloeckl.me
tagline: IT Consulting & Software Development
description: "Personal website of Moritz Glöckl - IT consulting and software development services based in Vienna, Austria."

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

exclude: [README.md]
